development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV.fetch("DDR_ADMIN_DB_NAME", "dul_hydra") %>
  pool: 5
  username: <%= ENV.fetch("DDR_ADMIN_DB_USER", "hydra") %>
  password: <%= ENV["DDR_ADMIN_DB_PASS"] %>
  host: 127.0.0.1
  port: 3306
